-- Script lu par l'app java

-- Drop Contraintes 
ALTER TABLE REALISATEURS 	DROP CONSTRAINT FKPERSONNE;
ALTER TABLE SCENARISTES 	DROP CONSTRAINT FKIDPERSONNE;
ALTER TABLE ROLES 			DROP CONSTRAINT FKPERSONNE_ROLES;
ALTER TABLE PERSONNES 		DROP CONSTRAINT PKIDPERSONNE;

-- Drop Table
DROP TABLE PERSONNES;

-- Creation Tables
CREATE TABLE PERSONNES (
  IDPERSONNE        INTEGER,
  NOM               VARCHAR(60),
  LIEUNAISSANCE     VARCHAR(90),
  PHOTO             VARCHAR(200),
  BIO               CLOB,
  ANNIVERSAIRE		DATE
);

-- Ajout Contrainte
ALTER TABLE PERSONNES ADD CONSTRAINT PKIDPERSONNE PRIMARY KEY (IDPERSONNE);
ALTER TABLE REALISATEURS ADD CONSTRAINT FKPERSONNE FOREIGN KEY (IDPERSONNE) REFERENCES PERSONNES (IDPERSONNE);
ALTER TABLE SCENARISTES ADD CONSTRAINT FKIDPERSONNE FOREIGN KEY (IDPERSONNE) REFERENCES PERSONNES (IDPERSONNE);
ALTER TABLE ROLES ADD CONSTRAINT FKPERSONNE_ROLES FOREIGN KEY (IDPERSONNE) REFERENCES PERSONNES (IDPERSONNE);   

COMMIT;