-- Script lu par l'app java

-- Drop Contraintes
ALTER TABLE INFOCREDIT  DROP CONSTRAINT PKINFOCREDIT;
ALTER TABLE INFOCREDIT  DROP CONSTRAINT FKINFOCREDIT;
ALTER TABLE INFOCREDIT  DROP CONSTRAINT CKEXPMOIS;
ALTER TABLE INFOCREDIT  DROP CONSTRAINT CKEXPANNE;

ALTER TABLE LOUER    DROP CONSTRAINT FKIDCLIENLOUER;
ALTER TABLE LOUER    DROP CONSTRAINT FKIDFILM_LOUER;

ALTER TABLE CLIENTS  DROP CONSTRAINT PKIDCLIENT;
ALTER TABLE CLIENTS  DROP CONSTRAINT CKCOURRIEL;

-- Drop Tables
DROP TABLE CLIENTS;
DROP TABLE INFOCREDIT;
DROP TABLE LOUER;

-- Create Tables
CREATE TABLE CLIENTS (
  IDCLIENT      INTEGER,
  PRENOM        VARCHAR(50),
  NOMFAMILLE    VARCHAR(50),
  ADRESSE       VARCHAR(50),
  VILLE         VARCHAR(50),
  PROVINCE      VARCHAR(50),
  CODEPOSTAL    VARCHAR(50),
  MOTDEPASSE    VARCHAR(50),
  FORFAIT       VARCHAR(1),
  COURRIEL      VARCHAR(50),
  NOTELEPHONE   VARCHAR(12),
  ANNIVERSAIRE  DATE
);

CREATE TABLE INFOCREDIT (
  CARTE       VARCHAR(20),
  NOCARTE     VARCHAR(20),
  EXPMOIS     INTEGER,
  EXPANNEE    INTEGER,
  IDCLIENT    INTEGER
);

CREATE TABLE LOUER(
  IDCLIENT      INTEGER,
  IDFILM        INTEGER
  );

-- Ajout Contraintes
ALTER TABLE CLIENTS ADD CONSTRAINT PKIDCLIENT  PRIMARY KEY (IDCLIENT);
ALTER TABLE CLIENTS ADD CONSTRAINT CKCOURRIEL CHECK (COURRIEL LIKE '%_@_%._%');

 ALTER TABLE INFOCREDIT MODIFY  NOCARTE   VARCHAR(20) NOT NULL;
 ALTER TABLE INFOCREDIT MODIFY  EXPMOIS   INTEGER NOT NULL;
 ALTER TABLE INFOCREDIT MODIFY  EXPANNEE  INTEGER NOT NULL;
 ALTER TABLE INFOCREDIT ADD CONSTRAINT PKINFOCREDIT  PRIMARY KEY (NOCARTE);
 ALTER TABLE INFOCREDIT ADD CONSTRAINT FKINFOCREDIT  FOREIGN KEY (IDCLIENT) REFERENCES CLIENTS (IDCLIENT);
 ALTER TABLE INFOCREDIT ADD CONSTRAINT CKEXPMOIS CHECK (EXPMOIS>=1 AND EXPMOIS<=12);
 ALTER TABLE INFOCREDIT ADD CONSTRAINT CKEXPANNE CHECK (EXPANNEE>=1900);

 ALTER TABLE LOUER ADD CONSTRAINT FKIDCLIENLOUER FOREIGN KEY (IDCLIENT) REFERENCES CLIENTS (IDCLIENT);
 ALTER TABLE LOUER ADD CONSTRAINT FKIDFILM_LOUER FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);

COMMIT;