-- PERSONNES
ALTER TABLE PERSONNES ADD CONSTRAINT PKIDPERSONNE PRIMARY KEY (IDPERSONNE);

 -- CLIENTS
ALTER TABLE CLIENTS ADD CONSTRAINT PKIDCLIENT  PRIMARY KEY (IDCLIENT);
ALTER TABLE CLIENTS ADD CONSTRAINT CKCOURRIEL CHECK (COURRIEL LIKE '%_@_%._%');

-- INFO CREDIT
 ALTER TABLE INFOCREDIT MODIFY  NOCARTE  	VARCHAR(20) NOT NULL;
 ALTER TABLE INFOCREDIT MODIFY  EXPMOIS  	INTEGER NOT NULL;
 ALTER TABLE INFOCREDIT MODIFY  EXPANNEE 	INTEGER NOT NULL;
 ALTER TABLE INFOCREDIT ADD CONSTRAINT PKINFOCREDIT  PRIMARY KEY (NOCARTE);
 ALTER TABLE INFOCREDIT ADD CONSTRAINT FKINFOCREDIT  FOREIGN KEY (IDCLIENT) REFERENCES CLIENTS (IDCLIENT);
 ALTER TABLE INFOCREDIT ADD CONSTRAINT CKEXPMOIS CHECK (EXPMOIS>=1 AND EXPMOIS<=12);
 ALTER TABLE INFOCREDIT ADD CONSTRAINT CKEXPANNE CHECK (EXPANNEE>=1900);

-- FILMS
 ALTER TABLE FILMS ADD CONSTRAINT PKFILMS PRIMARY KEY (IDFILM);

-- GENRES UNIQUE
 ALTER TABLE GENRES_UNIQUE ADD CONSTRAINT PKGENRE PRIMARY KEY (GENRE);

-- PAYS UNIQUE
 ALTER TABLE PAYS_UNIQUE ADD CONSTRAINT PKPAYS PRIMARY KEY (PAYS);

-- GENRES
 ALTER TABLE GENRES ADD CONSTRAINT FKGENRES  FOREIGN KEY (GENRE) REFERENCES GENRES_UNIQUE (GENRE);
 ALTER TABLE GENRES ADD CONSTRAINT FKIDFILMS FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);

-- PAYS
 ALTER TABLE PAYS ADD CONSTRAINT FKPAYS   FOREIGN KEY(PAYS) REFERENCES PAYS_UNIQUE (PAYS);
 ALTER TABLE PAYS ADD CONSTRAINT FKIDFILMS_PAYS FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);

-- REALISATEURS
 ALTER TABLE REALISATEURS ADD CONSTRAINT FKPERSONNE FOREIGN KEY (IDPERSONNE) REFERENCES PERSONNES (IDPERSONNE);
 ALTER TABLE REALISATEURS ADD CONSTRAINT FKFILMS_REALISATEUR FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);   

-- SCENARISTES
 ALTER TABLE SCENARISTES ADD CONSTRAINT FKIDPERSONNE FOREIGN KEY (IDPERSONNE) REFERENCES PERSONNES (IDPERSONNE);
 ALTER TABLE SCENARISTES ADD CONSTRAINT FKFILMS_SCENARISTE   FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);

-- ROLES
 ALTER TABLE ROLES ADD CONSTRAINT FKPERSONNE_ROLES FOREIGN KEY (IDPERSONNE) REFERENCES PERSONNES (IDPERSONNE);   
 ALTER TABLE ROLES ADD CONSTRAINT FKFILMS_ROLES FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);
 
 -- ANNONCES
ALTER TABLE ANNONCES ADD CONSTRAINT FKIDFILMS_ANNONCES FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);

-- LOUER
  ALTER TABLE LOUER ADD CONSTRAINT FKIDCLIENLOUER FOREIGN KEY (IDCLIENT) REFERENCES CLIENTS (IDCLIENT);
  ALTER TABLE LOUER ADD CONSTRAINT FKIDFILM_LOUER FOREIGN KEY (IDFILM) REFERENCES FILMS (IDFILM);