

DROP TABLE LOUER;
DROP TABLE INFOCREDIT;
DROP TABLE CLIENTS;
DROP TABLE GENRES;
DROP TABLE PAYS;
DROP TABLE GENRES_UNIQUE;
DROP TABLE PAYS_UNIQUE;
DROP TABLE REALISATEURS;
DROP TABLE SCENARISTES;
DROP TABLE ROLES;
DROP TABLE ANNONCES;
DROP TABLE FILMS;
DROP TABLE PERSONNES;


CREATE TABLE PERSONNES (
  IDPERSONNE        INTEGER,
  NOM               VARCHAR(60),
  LIEUNAISSANCE     VARCHAR(90),
  PHOTO             VARCHAR(200),
  BIO               CLOB,
  ANNIVERSAIRE      DATE
);

CREATE TABLE CLIENTS (
  IDCLIENT      INTEGER,
  PRENOM        VARCHAR(50),
  NOMFAMILLE    VARCHAR(50),
  ADRESSE       VARCHAR(50),
  VILLE         VARCHAR(50),
  PROVINCE      VARCHAR(50),
  CODEPOSTAL    VARCHAR(50),
  MOTDEPASSE    VARCHAR(50),
  FORFAIT       VARCHAR(1),
  COURRIEL      VARCHAR(50),
  NOTELEPHONE   VARCHAR(12),
  ANNIVERSAIRE  DATE
);

CREATE TABLE INFOCREDIT (
  CARTE       VARCHAR(20),
  NOCARTE     VARCHAR(20),
  EXPMOIS     INTEGER,
  EXPANNEE    INTEGER,
  IDCLIENT    INTEGER
);

CREATE TABLE FILMS (
  IDFILM        INTEGER,
  TITRE         VARCHAR(90),
  ANNEE         VARCHAR(50),
  LANGUE        VARCHAR(50),
  DUREE         VARCHAR(50),
  RESUME        VARCHAR(500),
  POSTER        VARCHAR(120)
);

CREATE TABLE GENRES_UNIQUE (
  GENRE       VARCHAR(90)
);

CREATE TABLE PAYS_UNIQUE (
  PAYS        VARCHAR(90)
);

CREATE TABLE PAYS (
  PAYS    VARCHAR (90),
  IDFILM  INTEGER
);

CREATE TABLE GENRES (
  GENRE    VARCHAR(90),
  IDFILM   INTEGER
);

CREATE TABLE REALISATEURS (
  IDPERSONNE     INTEGER,
  IDFILM         INTEGER
);

CREATE TABLE SCENARISTES (
  IDPERSONNE     INTEGER,
  IDFILM         INTEGER
);

CREATE TABLE ROLES (
  IDPERSONNE    INTEGER,
  PERSONNAGE    VARCHAR(90),
  IDFILM        INTEGER 
);

CREATE TABLE ANNONCES (
  LIEN        VARCHAR(500),  
  IDFILM      INTEGER
);

CREATE TABLE LOUER(
  IDCLIENT      INTEGER,
  IDFILM        INTEGER
  );

COMMIT;